import { useEffect,useMemo,useState } from "react";
import { ArrowDown, ArrowRight, BriefcaseBusiness, Check, ChevronDown, CircleHelp, Clock3, FileText, Filter, Globe2, LockKeyhole, LogOut, Menu, Search, ShieldCheck, Sparkles, Upload, Users, X } from "lucide-react";
import { configured,supabase } from "./lib/supabase";
import { signIn,signOut,signUp,type AppRole } from "./lib/auth";
type Job={id:string;title:string;department:string;location:string;type:string;description:string;created_at:string;};
type Profile={id:string;full_name:string;role:AppRole};
type Application={id:string;status:string;created_at:string;cv_path:string;job_id:string;jobs?:{title:string;department:string}};
type AdminJob=Job&{is_active:boolean;recruiter_id:string|null};
const demoJobs:Job[]=[
{id:"demo-1",title:"Frontend Developer",department:"Engineering",location:"Nowshera · Hybrid",type:"Full-time",description:"Build thoughtful digital experiences with a collaborative product team.",created_at:"2026-09-18"},
{id:"demo-2",title:"People Operations Associate",department:"People",location:"Nowshera · On-site",type:"Full-time",description:"Help our teams do their best work through welcoming, organized operations.",created_at:"2026-09-16"},
{id:"demo-3",title:"Product Designer",department:"Design",location:"Remote · Pakistan",type:"Contract",description:"Turn complex workflows into clear and useful product experiences.",created_at:"2026-09-12"},
{id:"demo-4",title:"Customer Success Specialist",department:"Operations",location:"Nowshera · Hybrid",type:"Full-time",description:"Partner with customers and make every interaction feel effortless.",created_at:"2026-09-10"}
];
const departments=["All roles","Engineering","Design","People","Operations"];
export default function App(){
const [jobs,setJobs]=useState<Job[]>(demoJobs),[profile,setProfile]=useState<Profile|null>(null),[applications,setApplications]=useState<Application[]>([]),[adminJobs,setAdminJobs]=useState<AdminJob[]>([]),[people,setPeople]=useState<Profile[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[query,setQuery]=useState(""),[dept,setDept]=useState("All roles"),[modal,setModal]=useState<Job|null| "auth" | "apply" | "dashboard" | null>(null),[authMode,setAuthMode]=useState<"signin"|"signup">("signup"),[selected,setSelected]=useState<Job|null>(null),[mobileOpen,setMobileOpen]=useState(false);
useEffect(()=>{if(!supabase)return; supabase.auth.getSession().then(({data})=>{if(data.session) void loadProfile()}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{if(s) window.setTimeout(()=>void loadProfile(),0); else {setProfile(null);setApplications([])}}); void loadJobs(); return()=>subscription.unsubscribe()},[]);
async function loadProfile(){try{if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data,error}=await supabase.from("profiles").select("id,full_name,role").eq("id",user.id).single();if(error)throw error;setProfile(data);if(data.role==="admin"){const [jr,pr]=await Promise.all([supabase.from("jobs").select("id,title,department,location,type,description,created_at,is_active,recruiter_id").order("created_at",{ascending:false}),supabase.from("profiles").select("id,full_name,role").order("created_at",{ascending:false})]);if(!jr.error)setAdminJobs((jr.data||[]) as AdminJob[]);if(!pr.error)setPeople((pr.data||[]) as Profile[])}const {data:apps}=await supabase.from("applications").select("id,status,created_at,cv_path,job_id,jobs(title,department)").order("created_at",{ascending:false});setApplications((apps||[]) as unknown as Application[])}catch(e){setNotice(err(e))}}
async function loadJobs(){if(!supabase)return;const {data,error}=await supabase.from("jobs").select("id,title,department,location,type,description,created_at").eq("is_active",true).order("created_at",{ascending:false});if(!error&&data?.length)setJobs(data as Job[])}
const filtered=useMemo(()=>jobs.filter(j=>(dept==="All roles"||j.department===dept)&&(`${j.title} ${j.department} ${j.location}`.toLowerCase().includes(query.toLowerCase()))),[jobs,dept,query]);
function openApply(j:Job){setSelected(j);setModal(profile?"apply":"auth");setAuthMode("signup")}
async function apply(file:File|null){if(!supabase||!profile||!selected||!file)return;setBusy(true);setNotice("");try{if(file.size>8*1024*1024)throw new Error("CV file must be under 8 MB.");if(!["application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"].includes(file.type))throw new Error("Please upload a PDF, DOC, or DOCX file.");const path=`${profile.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const {error:upError}=await supabase.storage.from("candidate-cvs").upload(path,file,{contentType:file.type,upsert:false});if(upError)throw upError;const {error}=await supabase.from("applications").insert({candidate_id:profile.id,job_id:selected.id,cv_path:path});if(error){await supabase.storage.from("candidate-cvs").remove([path]);throw error}const {data:created}=await supabase.from("applications").select("id").eq("candidate_id",profile.id).eq("job_id",selected.id).single();if(created?.id)void supabase.functions.invoke("notify-application",{body:{applicationId:created.id}});setNotice("Application received. We'll be in touch by email.");setModal(null);await loadProfile()}catch(e){setNotice(err(e))}finally{setBusy(false)}}
async function submitAuth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNotice("");const f=new FormData(e.currentTarget);try{const email=String(f.get("email")),password=String(f.get("password"));let hasSession=true;if(authMode==="signin")await signIn(email,password);else{const data=await signUp(email,password,String(f.get("full_name")));hasSession=Boolean(data.session);if(!data.session)setNotice("Check your inbox to confirm your email, then sign in.");}if(selected&&hasSession){setModal("apply")}else if(!selected&&hasSession)setModal(null)}catch(e){setNotice(err(e))}finally{setBusy(false)}}
async function downloadCv(app:Application){if(!supabase||!app.cv_path)return;const {data,error}=await supabase.storage.from("candidate-cvs").createSignedUrl(app.cv_path,60);if(error){setNotice(err(error));return}window.open(data.signedUrl,"_blank","noopener,noreferrer")}
async function createJob(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);try{const f=new FormData(e.currentTarget);const {error}=await supabase.from("jobs").insert({title:String(f.get("title")),department:String(f.get("department")),location:String(f.get("location")),type:String(f.get("type")),description:String(f.get("description")),is_active:true});if(error)throw error;setNotice("Role published.");await loadJobs();await loadProfile()}catch(e){setNotice(err(e))}finally{setBusy(false)}}
async function toggleJob(j:AdminJob){if(!supabase)return;setBusy(true);try{const {error}=await supabase.from("jobs").update({is_active:!j.is_active}).eq("id",j.id);if(error)throw error;setAdminJobs(x=>x.map(a=>a.id===j.id?{...a,is_active:!j.is_active}:a));await loadJobs();setNotice(j.is_active?"Role closed.":"Role reopened.")}catch(e){setNotice(err(e))}finally{setBusy(false)}}
async function changeRole(p:Profile,role:AppRole){if(!supabase||p.id===profile?.id)return;setBusy(true);try{const {error}=await supabase.from("profiles").update({role}).eq("id",p.id);if(error)throw error;setPeople(x=>x.map(a=>a.id===p.id?{...a,role}:a));setNotice("Account role updated.")}catch(e){setNotice(err(e))}finally{setBusy(false)}}
async function setStatus(app:Application,status:string){if(!supabase)return;setBusy(true);try{const {error}=await supabase.from("applications").update({status}).eq("id",app.id);if(error)throw error;setApplications(x=>x.map(a=>a.id===app.id?{...a,status}:a))}catch(e){setNotice(err(e))}finally{setBusy(false)}}
async function deleteApp(app:Application){if(!supabase||!confirm("Remove this application and its CV?"))return;setBusy(true);try{if(app.cv_path)await supabase.storage.from("candidate-cvs").remove([app.cv_path]);const {error}=await supabase.from("applications").delete().eq("id",app.id);if(error)throw error;setApplications(x=>x.filter(a=>a.id!==app.id));setNotice("Application removed.")}catch(e){setNotice(err(e))}finally{setBusy(false)}}
async function handleLogout(){try{await signOut();setModal(null)}catch(e){setNotice(err(e))}}
return <><header className="top"><a className="brand" href="#" onClick={e=>{e.preventDefault();setModal(null)}}><span className="brandmark">N</span><span>nowshera<span className="brandlight">digital</span></span></a><nav className={mobileOpen?"nav open":"nav"}><a href="#opportunities" onClick={()=>setMobileOpen(false)}>Find a role</a><a href="#about">Our story</a><a href="#process">How it works</a><button className="navmobile" onClick={()=>{setModal(profile?"dashboard":"auth");setMobileOpen(false)}}>{profile?"My workspace":"Candidate sign in"} <ArrowRight size={15}/></button></nav><div className="topactions"><button className="login" onClick={()=>setModal(profile?"dashboard":"auth")}>{profile?profile.full_name.split(" ")[0]:"Candidate sign in"} <ArrowRight size={16}/></button><button className="hamb" onClick={()=>setMobileOpen(!mobileOpen)} aria-label="Open menu"><Menu/></button></div></header>
<main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"></span> YOUR NEXT CHAPTER STARTS HERE</div><h1>Good work<br/>starts with <em>good people.</em></h1><p className="lede">Find a role where your ideas matter, your work has purpose, and your next step feels right.</p><div className="hero-buttons"><a className="button dark" href="#opportunities">Explore open roles <ArrowRight size={16}/></a><a className="textlink" href="#about">Get to know us <ArrowDown size={15}/></a></div><div className="proof"><div className="avatars"><i>F</i><i>A</i><i>S</i><i>+</i></div><span><b>A team that makes room</b><br/>for your kind of brilliant</span></div></div><div className="hero-art"><div className="art-sun"></div><div className="art-card"><div className="art-tag"><Sparkles size={13}/> A PLACE TO GROW</div><div className="art-quote">“Bring your whole<br/>self. Build what's<br/><em>next.</em>”</div><div className="art-bottom"><span>Nowshera Digital</span><span>01 — 04</span></div></div><div className="art-stamp"><Globe2 size={19}/><span>ROOTED HERE.<br/>OPEN EVERYWHERE.</span></div><div className="art-leaf leaf1"></div><div className="art-leaf leaf2"></div></div></section>
<section className="ticker"><span>BUILD WITH PURPOSE</span><b>✳</b><span>MAKE AN IMPACT</span><b>✳</b><span>GROW TOGETHER</span><b>✳</b><span>THINK BIGGER</span><b>✳</b><span>BUILD WITH PURPOSE</span></section>
<section className="roles section" id="opportunities"><div className="section-head"><div><div className="eyebrow green">THE OPPORTUNITIES</div><h2>Find your <em>place.</em></h2><p>Good people are the beginning of everything good.</p></div><div className="role-count">{filtered.length.toString().padStart(2,"0")} <span>OPEN ROLES</span></div></div><div className="filters"><div className="searchbox"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search roles, teams, locations"/></div><div className="deptfilters"><Filter size={15}/>{departments.map(d=><button key={d} className={dept===d?"chip active":"chip"} onClick={()=>setDept(d)}>{d}</button>)}</div></div><div className="joblist">{filtered.map((j,i)=><article className="job" key={j.id}><div className="jobnum">0{i+1}</div><div className="jobmain"><div className="jobchips"><span>{j.department}</span><i></i><span>{j.type}</span></div><h3>{j.title}</h3><p>{j.location}</p></div><div className="jobdesc">{j.description}</div><button className="roundarrow" aria-label={"View "+j.title} onClick={()=>setModal(j)}><ArrowRight size={18}/></button></article>)}{!filtered.length&&<div className="empty">No roles match those filters. Try another search.</div>}</div><div className="roles-foot"><span>Can't find the right fit?</span><a href="mailto:careers@nowsheradigital.com">Send us a note <ArrowRight size={15}/></a></div></section>
<section className="manifesto" id="about"><div className="manifesto-image"><div className="manifesto-circle"><span>ND</span></div><div className="image-caption">GOOD WORK IS A<br/>TEAM SPORT <b>✳</b></div></div><div className="manifesto-copy"><div className="eyebrow">A LITTLE ABOUT US</div><h2>Ambitious work.<br/><em>Grounded people.</em></h2><p>We’re building useful things for the people around us. That means staying curious, doing the thoughtful work, and leaving every project a little better than we found it.</p><p>Our team brings different paths and perspectives to the same table. There’s room here to learn, take ownership, and make a real difference.</p><a className="textlink light" href="#process">What working here looks like <ArrowRight size={15}/></a></div></section>
<section className="process section" id="process"><div className="eyebrow green">NO MYSTERY, NO MAZE</div><div className="process-title"><h2>A process made for <em>people.</em></h2><p>Clear steps. Thoughtful conversations.<br/>We’ll keep you in the loop.</p></div><div className="steps"><div><b>01</b><h3>Say hello</h3><p>Share a little about yourself and the work you’ve done.</p></div><div><b>02</b><h3>Meet the team</h3><p>Talk through the role, your ideas, and what matters to you.</p></div><div><b>03</b><h3>Find the fit</h3><p>We’ll be open about next steps and get back to you either way.</p></div></div></section>
<section className="closing"><div className="closing-mark">✳</div><div><div className="eyebrow">YOUR NEXT CHAPTER</div><h2>Make room for<br/><em>what's next.</em></h2></div><a className="button cream" href="#opportunities">See open roles <ArrowRight size={16}/></a></section></main>
<footer><a className="brand footerbrand" href="#"><span className="brandmark">N</span><span>nowshera<span className="brandlight">digital</span></span></a><span>Thoughtful work. Good people. Nowshera, Pakistan.</span><div><a href="mailto:careers@nowsheradigital.com">Contact</a><a href="#opportunities">Careers</a><a href="#about">About</a></div><small>© 2026 Nowshera Digital</small></footer>
{notice&&<div className="toast" role="status"><span>{notice}</span><button onClick={()=>setNotice("")}><X size={15}/></button></div>}
{modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className="dialog"><button className="close" onClick={()=>setModal(null)} aria-label="Close"><X/></button>
{typeof modal==="object"&&modal!==null&&<><div className="eyebrow green">{modal.department} · {modal.type}</div><h2>{modal.title}</h2><p className="dialogloc">{modal.location}</p><p>{modal.description}</p><div className="dialoglist"><span><Check size={16}/> Purposeful, collaborative work</span><span><Check size={16}/> Room to learn and grow</span><span><Check size={16}/> A kind, thoughtful team</span></div><button className="button dark wide" onClick={()=>openApply(modal)}>Apply for this role <ArrowRight size={16}/></button></>}
{modal==="auth"&&<><div className="eyebrow green">CANDIDATE PORTAL</div><h2>{authMode==="signin"?"Welcome back.":"Let’s get you started."}</h2><p>Sign in to manage your applications, or create a profile to apply.</p><form onSubmit={submitAuth} className="form">{authMode==="signup"&&<label>Your name<input name="full_name" required placeholder="Full name"/></label>}<label>Email address<input name="email" type="email" required placeholder="you@example.com"/></label><label>Password<input name="password" type="password" required minLength={8} placeholder="At least 8 characters"/></label><button className="button dark wide" disabled={busy}>{busy?"Please wait…":authMode==="signin"?"Sign in":"Create candidate account"} <ArrowRight size={16}/></button></form><div className="switch"> {authMode==="signin"?"New here?":"Already have an account?"} <button onClick={()=>setAuthMode(authMode==="signin"?"signup":"signin")}>{authMode==="signin"?"Create an account":"Sign in"}</button></div>{!configured&&<div className="confighint"><CircleHelp size={15}/> Demo preview. Connect Supabase to enable sign-in and applications.</div>}</>}
{modal==="apply"&&selected&&profile&&<><div className="eyebrow green">APPLICATION · {selected.department}</div><h2>Apply to {selected.title}.</h2><p>Upload your CV as a PDF, DOC, or DOCX file (8 MB max). Your application is visible only to you, assigned recruiters, and authorized admins.</p><label className="upload"><Upload size={22}/><b>Choose your CV</b><span>PDF, DOC, DOCX · up to 8 MB</span><input type="file" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>void apply(e.target.files?.[0]||null)}/></label>{busy&&<p className="uploading">Uploading securely…</p>}</>}
{modal==="dashboard"&&<><div className="eyebrow green">YOUR WORKSPACE</div><h2>Hello, {profile?.full_name.split(" ")[0]}.</h2><p>Your recent applications and their status.</p>{profile?.role==="admin"&&<section className="adminpanel"><h3>Manage roles</h3><form className="jobform" onSubmit={createJob}><input name="title" required placeholder="Role title"/><select name="department"><option>Engineering</option><option>Design</option><option>People</option><option>Operations</option><option>General</option></select><input name="location" required defaultValue="Nowshera · Hybrid"/><select name="type"><option>Full-time</option><option>Part-time</option><option>Contract</option></select><textarea name="description" required placeholder="Short role description"/><button className="button dark" disabled={busy}>Publish role <ArrowRight size={14}/></button></form><div className="adminrows">{adminJobs.map(j=><div key={j.id}><span><b>{j.title}</b><small>{j.department} · {j.location}</small></span><button disabled={busy} onClick={()=>void toggleJob(j)}>{j.is_active?"Close role":"Reopen role"}</button></div>)}</div><h3>Accounts & access</h3><p className="adminhint">Only verified staff should be assigned recruiter or admin access.</p><div className="adminrows">{people.map(p=><div key={p.id}><span><b>{p.full_name||"Candidate"}</b><small>{p.id===profile.id?"Your account":p.id}</small></span><select aria-label={"Role for "+p.full_name} disabled={busy||p.id===profile.id} value={p.role} onChange={e=>void changeRole(p,e.target.value as AppRole)}><option value="candidate">Candidate</option><option value="recruiter">Recruiter</option><option value="admin">Admin</option></select></div>)}</div></section>}<div className="applicationlist">{applications.length?applications.map(a=><div className="application" key={a.id}><div><b>{a.jobs?.title||"Application"}</b><small>{a.jobs?.department||"Nowshera Digital"} · {new Date(a.created_at).toLocaleDateString()}</small></div><span className={"status "+a.status}>{a.status.replace("_"," ")}</span>{(profile?.role==="admin"||profile?.role==="recruiter")&&<select className="statusselect" value={a.status} onChange={e=>void setStatus(a,e.target.value)} disabled={busy} aria-label="Update application status">{["submitted","reviewing","shortlisted","interview","rejected","hired"].map(v=><option key={v} value={v}>{v}</option>)}</select>}{a.cv_path&&<button title="Open CV" onClick={()=>void downloadCv(a)}><FileText size={17}/></button>}{profile?.role==="admin"&&<button title="Remove application" onClick={()=>void deleteApp(a)}><X size={17}/></button>}</div>):<div className="empty">You haven’t applied to a role yet. <a href="#opportunities" onClick={()=>setModal(null)}>Explore roles</a>.</div>}</div><div className="workspacefoot"><span><ShieldCheck size={16}/> Signed in as {profile?.role}</span><button onClick={()=>void handleLogout()}><LogOut size={15}/> Sign out</button></div></>}
</div></div>}
{!configured&&<div className="demobadge"><Sparkles size={14}/> Preview mode</div>}
</>
}
function err(e:unknown){return e instanceof Error?e.message:"Something went wrong. Please try again."}
